FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim

LABEL maintainer="devatherock@gmail.com"
LABEL io.github.devatherock.version="jdk-11.0.1.13-alpine-slim"

RUN apk update \
		&& apk add --no-cache docker