slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.7.0
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

work_directory: &work_directory
  working_directory: ~/docker-images

resource_class: &resource_class
  resource_class: small
  
pr_filter: &pr_filter
  filters:
    branches:
      ignore: master
      
merge_filter: &merge_filter
  filters:
    branches:
      only: master
  
executors:
  docker-executor:
    docker:
      - image: docker:19.03.6
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  dry_run_java_with_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f java-with-docker/Dockerfile .
  dry_run_graalvm_with_git:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --build-arg BASE_IMAGE_VERSION=ol8-java17-22.3.2 -f graalvm/Dockerfile .
  dry_run_nexmo_oas_renderer:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build nexmo-oas-renderer

  java_with_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/docker-images
      - run: |
          TAG=adoptopenjdk-11
          docker build -t devatherock/java-with-docker:$TAG -f java-with-docker/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/java-with-docker:$TAG
          
  graalvm_with_git:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/docker-images
      - run: |
          TAG=ol8-java17-22.3.2-1
          docker build --build-arg BASE_IMAGE_VERSION=ol8-java17-22.3.2 -t devatherock/graalvm:$TAG -f graalvm/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/graalvm:$TAG
          
  nexmo_oas_renderer:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/docker-images
      - run: |
          TAG=2.4.1-2
          docker build -t devatherock/nexmo-oas-renderer:$TAG nexmo-oas-renderer
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/nexmo-oas-renderer:$TAG

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack

workflows:
  version: 2.1
  build_publish:
    jobs:
      - java_with_docker:
          context:
            - docker-credentials
          <<: *merge_filter
      - graalvm_with_git:
          context:
            - docker-credentials
          <<: *merge_filter
      - nexmo_oas_renderer:
          context:
            - docker-credentials
          <<: *merge_filter
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - java_with_docker
            - graalvm_with_git
            - nexmo_oas_renderer
  pr_check:
    jobs:
      - dry_run_java_with_docker:
          context:
            - docker-credentials
          <<: *pr_filter
      - dry_run_graalvm_with_git:
          context:
            - docker-credentials
          <<: *pr_filter
      - dry_run_nexmo_oas_renderer:
          context:
            - docker-credentials
          <<: *pr_filter