slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

work_directory: &work_directory
  working_directory: ~/docker-images

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    docker:
      - image: docker:19.03.6
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  dry_run_java_with_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f java-with-docker/Dockerfile .
  dry_run_graalvm_with_git:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f graalvm/Dockerfile .

  java_with_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/docker-images
      - run: |
          TAG=adoptopenjdk-11
          docker build -t devatherock/java-with-docker:$TAG -f java-with-docker/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/java-with-docker:$TAG
  graalvm_with_git:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/docker-images
      - run: |
          TAG=20.2.0-java11
          docker build -t devatherock/graalvm:$TAG -f graalvm/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/graalvm:$TAG        

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#a1040c"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - java_with_docker:
          context:
            - docker-credentials
            - slack-webhook
          filters:
            branches:
              only: master
      - graalvm_with_git:
          context:
            - docker-credentials
            - slack-webhook
          filters:
            branches:
              only: master
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - java_with_docker
            - graalvm_with_git
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - java_with_docker
            - graalvm_with_git
  pr_check:
    jobs:
      - dry_run_java_with_docker:
          filters:
            branches:
              ignore: master
      - dry_run_graalvm_with_git:
          filters:
            branches:
              ignore: master